[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_ft = 'all'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
on_i = 1
on_ft = 'snippet'
on_unite = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = '.*'
on_cmd = 'VimFiler'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = '<Plug>'
on_cmd = 'VimShell'

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'cohama/vim-smartinput-endwise'
depends = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
pre_cmd = 'CtrlP'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'fatih/vim-go'
build = 'rm -Rf /usr/local/opt/macvim-kaoriya/MacVim.app/Contents/Resources/vim/plugins/golang'
on_ft = 'go'

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = 'less'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css', 'less']

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'majutsushi/tagbar'
pre_cmd = 'Tagbar'

[[plugins]]
repo = 'marijnh/tern_for_vim'
build = 'npm install'
on_ft = 'javascript'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'marcus/rsense'
build = "find doc -name '*.ja.txt' -print0 | perl -pe 's/\.txt\0/\0/g' | xargs -0 -I% mv %.txt %x"
on_ft = 'ruby'
on_i = 1

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'supermomonga/neocomplete-rsense.vim'
depends = 'marcus/rsense'
on_ft = 'ruby'
on_i = 1

[[plugins]]
repo = 'thinca/vim-themis'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-scripts/Colour-Sampler-Pack'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'vim-scripts/tagbar-phpctags'
build = 'curl -s http://vim-php.com/phpctags/install/phpctags.phar -o bin/phpctags.php && chmod +x bin/phpctags.php'
on_ft = 'php'
