[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'echo "Sorry, cannot update vimproc binary file in Windows."'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  unix    = 'make -f make_unix.mak'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/buftabs'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'vim-scripts/yanktmp.vim'
