[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_ft = 'all'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
on_i = 1
on_ft = 'snippet'
on_unite = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

  [plugins.on_cmd]
  name = 'Unite'
  complete = 'customlist,unite#complete_source'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = '.*'

  [plugins.on_cmd]
  name = ['VimFiler']
  complete = 'customlist,vimfiler#complete'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = '<Plug>'

  [plugins.on_cmd]
  name = 'VimShell'
  complete = 'customlist,vimshell#complete'

[[plugins]]
repo = 'Shougo/vinarise.vim'

  [plugins.on_cmd]
  name = 'Vinarise'
  complete = 'file'

[[plugins]]
repo = 'castor4bit/inside-motion.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'cohama/vim-smartinput-endwise'
depends = 'kana/vim-smartinput'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

  [plugins.build]
  mac     = 'rm -Rf /usr/local/opt/macvim-kaoriya/MacVim.app/Contents/Resources/vim/plugins/golang'

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = 'less'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css', 'less']

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'majutsushi/tagbar'
on_map = '<Plug>'

[[plugins]]
repo = 'marijnh/tern_for_vim'
build = 'npm install'
on_ft = 'javascript'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'marcus/rsense'
build = "find doc -name '*.ja.txt' -print0 | perl -pe 's/\.txt\0/\0/g' | xargs -0 -I% mv %.txt %x"
on_ft = 'ruby'
on_i = 1

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'supermomonga/neocomplete-rsense.vim'
depends = 'marcus/rsense'
on_ft = 'ruby'
on_i = 1

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-scripts/Colour-Sampler-Pack'

[[plugins]]
repo = 'vim-scripts/FuzzyFinder'
depends = 'vim-scripts/L9'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'vim-scripts/tagbar-phpctags'
build = 'curl -s http://vim-php.com/phpctags/install/phpctags.phar -o bin/phpctags.php && chmod +x bin/phpctags.php'
on_ft = 'php'
