tap 'homebrew/dupes'
tap 'josegonzalez/php'
tap 'phinze/cask'
install antiword
install asciidoc
install autoconf
install automake
install bats
install brew-cask
install byobu
install cairo
install cloud-watch
install cmake
install colordiff
install coreutils
install ctags
install curl
install docbook
install docbook-xsl
install ec2-api-tools
install erlang
install faac
install ffmpeg
install fontconfig
install fontforge
install freetype
install gawk
install gdbm
install gettext
install git
install glib
install gnu-getopt
install gnu-sed
install gnu-tar
install gobject-introspection
install groonga
install groonga-normalizer-mysql
install harfbuzz
install htop-osx
install httpd
install hub
install icu4c
install jenkins
install jpeg
install lame
install libevent
install libffi
install libiconv
install libmemcached
install libogg
install libpng
install libtiff
install libtool
install libvorbis
install libxml2
install libyaml
install lsof
install lynx
install mcrypt
install memcached
install mercurial
install mhash
install mongodb
install msgpack
install mysql
install newt
install nginx
install oniguruma
install openssl
install pango
install pcre
install phantomjs
install php-build
install php-version
install phpenv
install pidof
install pixman
install pkg-config
install play
install popt
install potrace
install pstree
install pwgen
install python
install rbenv
install re2c
install readline
install redis
install rsense
install rtmpdump
install ruby-build
install s-lang
install s3cmd
install scala
install screen
install sqlite
install syck
install texi2html
install the_silver_searcher
install tig
install tmux
install tree
install unixodbc
install wget
install wxmac
install x264
install xmlto
install xvid
install xz
install yasm
install z
install zlib
install zsh
